### ISSUE TITLE
软件启动后，“帮助引导”无法隐藏

### ISSUE THREAD

**Issue by lvsoso** [zhengying/Hungrymark-issue#1]
软件启动后，“帮助引导”无法隐藏，重启也不可以
![](https://tva1.sinaimg.cn/large/006y8mN6ly1g7yomooy8pj30gs0c50y4.jpg)

Mac Book 2017 
![](https://tva1.sinaimg.cn/large/006y8mN6ly1g7yolmpe67j306p04jwev.jpg)

**Comment by zhengying** [comment]
是左上角关闭点击无效？
还是即使点击了关闭启后引导但重启软件会重新出现？

**Comment by zhengying** [comment]
can't reproduce the problem, 
close in 1.2.01, if someone reproduces the problem, reopen it again.
