### ISSUE TITLE
可执行文件无法打开，因为不允许“Hungrymark”在“终端”中打开文稿

### ISSUE THREAD

**Issue by haosemusi** [zhengying/Hungrymark-issue#10]
预置条件：设置-书签点击行为 设置为“直接打开”

这种有什么方法可以解决吗？

**Comment by zhengying** [comment]
你的可执行文件是个脚本吗？目前只能打开有bundle 的app。  
脚本，没有bundle的可执行文件，还有点问题，我正在处理这个问题。希望下个版本加上

**Comment by haosemusi** [comment]
OK,辛苦哈

**Comment by zhengying** [comment]
先别关了，等fix后再关闭吧

**Comment by zhengying** [comment]
1.2.0 已经解决

**Comment by swimmingchar** [comment]
这个怎么解决的呀？我自己写了一个MAC的app,放在其他电脑上也包这个错，可是我已经给了他 755 的权限了呀

**Comment by zhengying** [comment]
> 这个怎么解决的呀？我自己写了一个MAC的app,放在其他电脑上也包这个错，可是我已经给了他 755 的权限了呀
你直接打开可以，但是放在hunrymark里面不行吗？
这个app是控制台程序，还是带bundle的？

**Comment by zhengying** [comment]
> 这个怎么解决的呀？我自己写了一个MAC的app,放在其他电脑上也包这个错，可是我已经给了他 755 的权限了呀

你直接打开可以，但是放在hunrymark里面不行吗？
这个app是控制台程序，还是带bundle的？
