### ISSUE TITLE
White space needed before bookmark file name in the "Settings -> Select bookmark file" menu item 

### ISSUE THREAD

**Issue by VKondakoff** [zhengying/Hungrymark-issue#11]
Small cosmetic issue: there is white space needed before bookmark file name in the "Settings -> Select bookmark file" menu item. 

<img width="435" alt="Image on 2019-10-28 01 37 01 PM" src="https://user-images.githubusercontent.com/230824/67672180-724c9200-f988-11e9-84fa-364e27f28927.png">

Catalina, Hungrymark v 1.1.6

**Comment by zhengying** [comment]
OK next version, thanks VKondakoff.

**Comment by zhengying** [comment]
fixed in 1.2.01
