### ISSUE TITLE
Keyboard hotkey functionality

### ISSUE THREAD

**Issue by VKondakoff** [zhengying/Hungrymark-issue#13]
I strongly suggest to add a keyboard hotkey functionality to Hungrymark. Here is a proposal: 
1. Assign a keyb. hotkey to open Hungrymark popup (let's say: "Alt+Space")
2. Assign predefined keyb. hotkeys to first ten items in the list (1, 2, ..., 9, 0). (The hotkeys should be added only to the items, which are specified in the bookmark file, not to the contents of the folders).

<img width="346" alt="Image on 2019-10-28 02 05 57 PM" src="https://user-images.githubusercontent.com/230824/67674338-4b448f00-f98d-11e9-9d53-781ab6292400.png">

<img width="402" alt="Image on 2019-10-28 02 06 25 PM" src="https://user-images.githubusercontent.com/230824/67674384-62837c80-f98d-11e9-8fd7-9882769c163b.png">

So in this quick mockup example the Hungrymark keyb. hotkey system might work like this:

a) To open Visual Studio Code: press "Alt+Space", 1, 2
b) To open Video share: press "Alt+Space", 2, 4

What do you think? Let's discuss this?

**Comment by zhengying** [comment]
Thanks, VKondakoff, 
Your suggestion is very similar to what I thought before, yours is better, I will add this function, maybe version 1.3, I am busy with plug-in function at present

**Comment by VKondakoff** [comment]
Thanks. Ping me if you want to discuss the issue, or need some testing.

**Comment by VKondakoff** [comment]
I'm glad Hungrymark is in active development recently. 
Any chance to see hotkey implementation in the near future? As a keyboard hotkey oriented user, I really miss the ability to open Hungrymark pop-up with keyboard hotkey instead of mouse click.

**Comment by zhengying** [comment]
@VKondakoff
Sorry, I didn't notice your message until now，
shortcut function is working, these two days, I will release it

**Comment by VKondakoff** [comment]
👍

**Comment by zhengying** [comment]
released in 1.2.6
