### ISSUE TITLE
收藏 JAR 文件不能打开。

### ISSUE THREAD

**Issue by yanwen** [zhengying/Hungrymark-issue#14]
无法打开“V1.0.jar”，因为不允许“Hungrymark”打开 Java JAR 文件。

**Comment by zhengying** [comment]
已经修复了，版本在审核中，这次修改了脚本 Runner 文件，升级后请 删除 ~/Library/Application\ Scripts/com.zhengying.hungrymark/HMRunner.sh 再试，谢谢反馈
