### ISSUE TITLE
Bug/Req: Allow different URL-schemes when defining bookmarks

### ISSUE THREAD

**Issue by VKondakoff** [zhengying/Hungrymark-issue#17]
Hello!

Just noticed, that Hungrymark Version 1.2.3 (13) allows only the default URL-scheme when defining bookmarks. There is an error if you want to save an URL with different URL-scheme using Hungrymark GUI. If you edit the default.txt file manually, the URL with different URL-scheme just does not appears in the list of available URLs.

In the following example I'm trying to add an URL to execute Keyboard Maestro macro:

<img width="652" alt="Скриншот 2020-04-28 13 40 46" src="https://user-images.githubusercontent.com/230824/80479356-91d46f80-8957-11ea-8bcb-752bd8c3b6a5.png">

**Comment by zhengying** [comment]
Hi VKondakoff, I'm glad you're still using hungrymark
different URL-scheme support is under development, I received many emails for this feature, I think it will be added in 1.3.0,  you can use AppleScript or shell script to workaround,  thanks again VKondakoff, I still owe you several issues, I hope I can finish them in 1.3.0.  Any problem, please let me known.

**Comment by VKondakoff** [comment]
Great, eagerly waiting for 1.3!

**Comment by zhengying** [comment]
supported in 1.3.0
