### ISSUE TITLE
Want edit bookmark by file back.

### ISSUE THREAD

**Issue by Yannmm** [zhengying/Hungrymark-issue#18]
Today when adding a bookmark to a group, I just found the way to do that changes a lot. The tutorial is not very clear, and I just found it involves a lot of drag and click. Programmers won't like it. Please allow user to edit bookmark just by directly editing the file, the old-fashioned way. Thanks.

**Comment by zhengying** [comment]
You can use the old-fashioned way. 
 Settings->Select bookmark file->Edit by file editor

**Comment by zhengying** [comment]
Any problem, please let me known
