### ISSUE TITLE
How to delete bookmark file?

### ISSUE THREAD

**Issue by jkantor** [zhengying/Hungrymark-issue#19]
I imported my Safari bookmarks - which include bookmarks from the last 20 years - over 20,000 of them! Your app can't handle that many - which is understandable, so I want to delete the bookmark file and just use Hungrymark for new bookmarks. How do I delete the Hungrymark bookmark file? Every time I launch it, even after uninstalling and reinstalling, it loads all those bookmarks again - which literally takes over an hour.

**Comment by zhengying** [comment]
Hi Jkantor
I already reply to your email,  I want to know whether this problem has been solved.

bookmark files in 
$HOME/Library/Containers/com.zhengying.hungrymark/Data/Documents/Workspace/

**Comment by zhengying** [comment]
Any problem please let me known.
