### ISSUE TITLE
Shortcut key cannot be disabled by default every time Hungrymark launches

### ISSUE THREAD

**Issue by Emrys365** [zhengying/Hungrymark-issue#20]
I found the default shortcut key of Hungrymark conflict with other apps, and then I tried to disable it.
However, the next time I launch this app, it cannot remember my previous setting, and enables the shortcut key again.

Could you fix this somehow?

**Comment by zhengying** [comment]
fixed, it'will release in the next version.
Thanks for your report

**Comment by zhengying** [comment]
fixed in 1.3.0
