### ISSUE TITLE
设置菜单bug

### ISSUE THREAD

**Issue by qq420100523** [zhengying/Hungrymark-issue#22]
通过ctrl+opt+com+m快捷键触发菜单显示后，用方向键选择到“设置”菜单后，无法从子菜单回到上级菜单。

**Comment by zhengying** [comment]
已经确认这个问题存在，而且在所有存在上级菜单并且存在下级菜单时候就会出现，我马上调查这个问题，
感谢你的反馈。

**Comment by zhengying** [comment]
设置菜单不能返回的问题已经在1.3.3中解决
