### ISSUE TITLE
请问到底怎么添加程序啊，直接输入路径或者拖动都只会在文件夹里显示而不是启动 app

### ISSUE THREAD

**Issue by loikein** [zhengying/Hungrymark-issue#24]
如题……

**Comment by zhengying** [comment]
你看看你设置里面，是不是设置成在finder中查看了，你先看看，如果有问题再联系我，发邮件，这里回复都可以

**Comment by zhengying** [comment]
<img width="590" alt="Screen Shot 2021-02-27 at 11 02 24 AM" src="https://user-images.githubusercontent.com/1042545/109373679-4ed28800-78eb-11eb-95af-1501a996c2be.png">
这个设置是直接运行，如果你是这个设置，请告诉我你的系统版本，谢谢

**Comment by loikein** [comment]
噢噢改了之后可以了，感谢解答。
