### ISSUE TITLE
iOS App

### ISSUE THREAD

**Issue by ChristinWhite** [zhengying/Hungrymark-issue#25]
Any chance you're planning an iOS app at some point? Obviously it would need to be a bit more limited for adding items but a lot of app URL schemes are supported on iOS.

**Comment by zhengying** [comment]
Yes, I have a plan,  maybe it will happen in the second half of this year, but I can't promise.
Thanks for your attention.

**Comment by ChristinWhite** [comment]
Excellent, thanks! I went ahead and purchased it!
